note: 'Faster training'

data_params:
  fold: 0
  n_splits: 5
  seed: 1

module_params:
  optim: adam
  lr: 3e-4
  weight_decay: 0.
  batch_size: 8
  drop_rate: 0.2
  drop_path_rate: 0.2

trainer_params:
  epochs: 200
  gpus: -1
  precision: 16
